# Generated by Django 2.2.16 on 2022-07-21 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220719_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.TextField(unique=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.TextField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время - 1 минута!')], verbose_name='Время приготовления (м.)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='backend/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='foodgram.Ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='foodgram.Tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текствое описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#ff0006', 'Красный'), ('#879eee', 'Голубой'), ('#220e75', 'Синий'), ('#e784f4', 'Розовый'), ('#8fd8b9', 'Светло зелёный'), ('#faad62', 'Светло оранжевый'), ('#deec59', 'Жёлтый'), ('#7e4bf3', 'Фиолетовый')], default='#ffffff', max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
